"""Add is_active to user

Revision ID: 17c15011bf88
Revises: 
Create Date: 2026-05-11 17:57:25.220018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17c15011bf88'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add the column as nullable first
    op.add_column('users', sa.Column('is_active', sa.Integer(), nullable=True))
    
    # 2. Set existing rows to 1 (active)
    op.execute("UPDATE users SET is_active = 1")
    
    # 3. Now make it non-nullable
    op.alter_column('users', 'is_active', nullable=False)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
